modLoader = "javafml"
loaderVersion = "*"
license = "MIT"

[[mods]]
modId = "e4all"
version = "${version}"
displayName = "e4all"
logoFile = "e4all_icon.png"
credits = "skyevg (original e4mc)"
authors = "JustPixel"
description = '''
The e4mc fork that lets anyone join your LAN world from anywhere, even with offline accounts.
'''

[[dependencies.e4all]]
modId = "forge"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.e4all]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,1.22)"
ordering = "NONE"
side = "BOTH"